language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra
    - sys-img-armeabi-v7a-android-19
  jdk:
    - oraclejdk7
    - openjdk7
install: ant deps
before_install:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &